import { initStoryblok } from '../lib/storyblok';
import StoryblokProvider from '../components/StoryblokProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface RootLayoutType {
  children: React.ReactNode;
}

initStoryblok();

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <body>
        <StoryblokProvider>{children}</StoryblokProvider>
      </body>
    </html>
  );
}
